version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    ports:
      - "8089:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminadmin
    volumes:
      - "./keycloak:/opt/keycloak/data"
    command:
      - start-dev
    networks:
      - cashflow-microservice-network
  proxy:
    image: nginx-app-img:latest
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cashflow-microservice-network
  db_report:
    image: postgres
    container_name: db_report
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Ora1626X
      POSTGRES_DB: report_cash_flow
    networks:
      - cashflow-microservice-network

  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    networks:
      - cashflow-microservice-network
  zookeeper:
    image: "bitnami/zookeeper:3.6.1"
    container_name: zookeeper
    networks:
      - cashflow-microservice-network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:2.5.0"
    container_name: kafka
    networks:
      - cashflow-microservice-network
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

networks:
  cashflow-microservice-network:
    driver: bridge
