server:
  port: 8080

logging:
  level: INFO

spring:
  application:
    name: cashflow-microservice
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    #    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    time-zone: America/Sao_Paulo

  cassandra:
    keyspace-name: "${KEYSPACE_NAME:cashflow}"
    port: 9042
    contact-points: ${CASSANDRA_SERVER:cassandra}
    local-datacenter: ${CASSANDRA_DATACENTER:datacenter1}
    schema-action: CREATE_IF_NOT_EXISTS

  sql:
    init:
      platform: postgres

  datasource:
    url: "jdbc:postgresql://${REPORT_DB_HOST:db}:5432/${REPORT_DB:report_cash_flow}"
    username: "${REPORT_DB_HOST:root}"
    password: "${REPORT_DB_PASSWORD:Ora1626X}"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true


  security:
    oauth2:
      #      client:
      #        registration:
      #          keycloak:
      #            client-id: api-billing-app
      #            authorization-grant-type: authorization_code
      #            scope: openid
      #        provider:
      #          keycloak:
      #            issuer-uri: http://localhost:8080/realms/greenhouse
      #            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/greenhouse
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json

  data:
    cassandra:
      create-keyspace: true

  # Kafka
  kafka:
    producer:
      retries: 5
      acks: all

  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          autoAddPartitions: true
          configuration:
            isolation:
              level: read_committed
          brokers: ${KAFKA_BROKERS:kafka:9092}
      function:
        definition: upsertItemCashFlow;reportCashFlow
      bindings:
        upsertItemCashFlow-in-0:
          destination: cashflow-upsert-item-cashflow-persist
          group: ${spring.application.name}

        reportCashFlow-in-0:
          destination: cashflow-report
          group: ${spring.application.name}
