server:
  port: 8080

logging:
  level: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
    enabled-by-default: true
  auditevents:
    enabled: true
  endpoint:
    health:
      enabled: true
  health:
    db:
      enabled: true
    cassandra:
      enabled: true
    binders:
      enabled: true



spring:
  application:
    name: cashflow-microservice
#  main:
#    allow-bean-definition-overriding: true
#    allow-circular-references: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    #    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    time-zone: America/Sao_Paulo

  cassandra:
    keyspace-name: "${KEYSPACE_NAME:cashflow}"
    port: 9042
    contact-points: ${CASSANDRA_SERVER:localhost}
    local-datacenter: ${CASSANDRA_DATACENTER:datacenter1}
    schema-action: CREATE_IF_NOT_EXISTS

  sql:
    init:
      platform: postgres

  datasource:
    url: "jdbc:postgresql://${REPORT_DB_HOST:localhost}:5432/${REPORT_DB:report_cash_flow}"
    username: "${REPORT_DB_USERNAME:root}"
    password: "${REPORT_DB_PASSWORD:Ora1626X}"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8089}/realms/cashflow"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  # Kafka
  kafka:
    producer:
      retries: 5
      acks: all

  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          autoAddPartitions: true
          configuration:
            isolation:
              level: read_committed
          brokers: ${KAFKA_BROKERS:localhost:9092}
      function:
        definition: upsertItemCashFlow
      bindings:
        upsertItemCashFlow-in-0:
          destination: cashflow-upsert-item-cashflow-persist
          group: ${spring.application.name}

jwt:
  auth:
    converter:
      resource-id: cashflow-client
      principal-attribute: preferred_username

report.filename: cash_flow.jasper
cql.keyspace: "CREATE KEYSPACE ${spring.cassandra.keyspace-name} WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};"
